id: PDDE60E01
initial_creation_type: ocr
source_metadata:
  volumes:
    8af2e4575ace48968f0de1b614aee68a:
      base_file: v051.txt
      image_group_id: I1PD95896
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་སྟོང་ཕྲག་ཉི་ཤུ་ལྔ་པ།
      total_pages: 1818
      volume_number: 51
