id: PDDE60E01
initial_creation_type: ocr
source_metadata:
  volumes:
    a483763bd7bd447b94aa58dbd1018776:
      base_file: v051.txt
      image_group_id: I1PD95896
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་སྟོང་ཕྲག་ཉི་ཤུ་ལྔ་པ།
      total_pages: 1818
      volume_number: 51
